# Generated by Django 4.2.8 on 2023-12-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zapis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=100, verbose_name='ФИО')),
                ('date_bith', models.DateField(verbose_name='Дата рождения')),
                ('categoty', models.CharField(max_length=50, verbose_name='Категория врача')),
                ('date', models.DateTimeField(verbose_name='Дата и время записи')),
                ('number', models.IntegerField(verbose_name='Номер телефона')),
            ],
        ),
    ]
