# Generated by Django 4.2.8 on 2023-12-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vrahi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=100, verbose_name='ФИО')),
                ('category', models.CharField(max_length=50, verbose_name='Категория врача')),
                ('stag', models.CharField(max_length=2, verbose_name='Стаж работы')),
                ('date', models.DateField(verbose_name='Даты работы')),
                ('time', models.TimeField(verbose_name='Часы работы')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.AlterModelOptions(
            name='zapis',
            options={'verbose_name': 'Запись на прием', 'verbose_name_plural': 'Запись на прием'},
        ),
    ]
