# Generated by Django 4.2.8 on 2023-12-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_vrahi_alter_zapis_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zapis',
            old_name='categoty',
            new_name='category',
        ),
    ]
