# Generated by Django 4.2.8 on 2023-12-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0003_rename_categoty_zapis_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrahi',
            name='date',
            field=models.CharField(max_length=30, verbose_name='Дни работы'),
        ),
        migrations.AlterField(
            model_name='vrahi',
            name='time',
            field=models.CharField(max_length=30, verbose_name='Часы работы'),
        ),
    ]
